apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.3.0
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.7.1
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true