
services:
  portainer:
    image: portainer/portainer-ee:2.31.3
    container_name: portainer-ee
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      PUID: 1000
      PGID: 1000
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
    - 8000:8000
    - 9443:9443
volumes:
  portainer:
    name: portainer


    