apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik
    version: v37.1.1
    valuesFile: values.yaml

resources:
  - ./ns.yaml
  - ./cluster-issuer.yaml
  - ./certificate.yaml