---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andsidor/Homelab-argocd
    targetRevision: master
    path: apps/app1/overlays
    kustomize:
      namePrefix: "demo-"
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

